app = "discord-bot-deus"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
builder = "heroku/buildpacks:20"

[env]
PORT = "8080"
LOGGING = "INFO"
PROFILE = "PROD"
COOKIE = "VISITOR_INFO1_LIVE=CRkDj5Yo9vY; _ym_uid=1634993767974270875; PREF=tz=Europe.Moscow&f6=40000000&f5=20000; _ym_isad=1; GPS=1; YSC=X1vBAhrYOA8; SID=LwhAXS1HQ0uGBP50V8lXLqc7TudKE-xrwJSkPT0k2Wjaq8FqttxfXtGpBcCDbuSBIgl3DQ.; __Secure-1PSID=LwhAXS1HQ0uGBP50V8lXLqc7TudKE-xrwJSkPT0k2Wjaq8FqhEefGUR_Vw2OkS24gBU6GQ.; __Secure-3PSID=LwhAXS1HQ0uGBP50V8lXLqc7TudKE-xrwJSkPT0k2Wjaq8FqTB1asQId0J5Nt40MGIuP1Q.; HSID=Atkz9K_Xh0gzJy3Xc; SSID=A41G2DCDWCk0WA-ef; APISID=c7gLqzkGrioonuyf/AYu5JHmCge2svX__n; SAPISID=RNCYceuarZYtMHtS/A9T8yBh7NJQIJSQxB; __Secure-1PAPISID=RNCYceuarZYtMHtS/A9T8yBh7NJQIJSQxB; __Secure-3PAPISID=RNCYceuarZYtMHtS/A9T8yBh7NJQIJSQxB; LOGIN_INFO=AFmmF2swRQIhAOr4Q9WKU-dn_zHSLaEO9XK43JSp2Lqc_aoQE2rwCzauAiB4PCc_6zM_ii53gYlruBZ3YcvWcdWUihdV0I1qgCivcg:QUQ3MjNmeUFyZGwwY2cwM2xSYWU2d0VVd3RvZmVFa2VCZTU3UUpRbmxqcmZXNy1NYTRTend3UW9hdmc0OUlKNDVwbEo5eGJ6RHB4U3k2SFNES0ZiLUpEeGdfeVBWc01wVUw5dXpWVlZZYkVpTEU3OE93elpMQkF2UzRzdVBZVHdFSThScTRrYi1GTnJkZnVFbTJoNENxQXlZeTVGQ1JhcVd3; CONSISTENCY=ALOGzFyUeLqwZ-O6vDi5tjwoQl1C-HKrUKbWWyhuZ28YknELHazaSfcIAulRW60Jk92IkaHfUjCzkYGDWxDOafuWWp1nKbwz8Gzj5Sh9e0R6lHm6hh1qpi5tug4RjXSIPxc7WeGSflpZS94cdPOMx_Mb; SIDCC=AJi4QfHAbYvjpfHSk0VNwovY5KkVypGzHZxyuykxDk3zwQzA1i44oAio-9JIkFthHYxqWl4lug; __Secure-1PSIDCC=AJi4QfEcLHRVDWqUFFfvCiGq-xUZIhWR99FtUZctbCxvceoaQRJWDp1ilJqUMtyQsTbV2d6H; __Secure-3PSIDCC=AJi4QfGoJv0UH2PIRP22buVbyZdztdvod1GKOxwZPfra3b5QTyozaPsgLcm3xRyHSHAcXCmhhA"
DEUS_BOT_WEB_URL = "https://discord-bot-deus-web.herokuapp.com"
GITHUB_LOGIN = "dafatov"
GITHUB_REPOSITORY = "DeusBot"

[experimental]
allowed_public_ports = []
auto_rollback = true

[[services]]
http_checks = []
internal_port = 8080
processes = ["app"]
protocol = "tcp"
script_checks = []
[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"
